### ISSUE TITLE
FAIL TO LOAD REMOTE FIRMWARE

### ISSUE THREAD

**Issue by mdmanmike** [cleanflight/cleanflight-configurator#122]
while attempting to "Load online firmware " Firmware does not load and error message appears "Fail to Load Remote Firmware" this appears regardless which firmware or FC you select.

**Comment by thenickdude** [comment]
Fixed in the latest version already, please update to the latest configurator:

In Chrome click the menu button, then More Tools, then Extensions
At the top of the page, tick the "developer mode" tickbox.
Click the "update extensions now" button

You should see the version number next to the Cleanflight Configurator tick over to the latest version (0.62.1) after a minute or so.
