### ISSUE TITLE
PID Tuning - Allow PIDs to be reset to firmware defaults.

### ISSUE THREAD

**Issue by RandGH** [cleanflight/cleanflight-configurator#133]
It would be nice if there was a reset to default values button in the gui to revert any ill modifications being done.

Additionally it would be great if PIDs could be saved *per* Pid Controller as those need very different values and other PidC's values might actually be harmfull.

**Comment by peisel** [comment]
This would really helpful!

**Comment by hydra** [comment]
The FC would need to expose PID defaults to the GUI.  Please open an issue in the firmware issue tracker and link to this.

**Comment by hydra** [comment]
@RandGH please keep issues focussed.  One issue per request.

This issue is for allowing pids to be reset to the firmware defaults.  With regards to the other topic you mentioned.  No.  Though I think changing pid controller should probably reset all pids to their pid controller defaults.  Please open a new issue to discuss this second topic further and provide a link to this comment in it.

**Comment by jrauch67** [comment]
Hi, have you created the issue to expose PID defaults in the firmware issue tracker ?

**Comment by skaman82** [comment]
already done
