### ISSUE TITLE
Waiting for Data Error after save and reboot

### ISSUE THREAD

**Issue by Tabsy123** [cleanflight/cleanflight-configurator#265]
After any tab that has save and reboot clicked or save in cli etc,  the configurator then says "Waiting for Data"  and never works again ,  I have to disconnect from the FC  and connect again,   I have tried latest 0.67 dev and normal configurator , also tried multiple versions of Cleanflight on the FC and tried my 2 different windows computers and also tried 3 different Naze32 boards,  all do this every single time.   Its a Pain in the arse when setting up a new board and you have to save and reboot the board often.
Strange thing is tho it does not do it on my daughters Mac running normal mac osx,  it works perfect 

When it faults on the windows pc's (every time for me) in the top windows it says that the device is rebooting in red,  but never returns to say the device is ready in green like it used to before this fault started to happen.

**Comment by fbrcdx** [comment]
Exactly the same issue for me.

**Comment by JohnOCFII** [comment]
The issue has been resolved in the master version of the code.  The fix is actually in the firmware code and not the configurator code (although the problem became apparent due to a Chrome change).

See the link for more details:  https://github.com/cleanflight/cleanflight/pull/1436

I don't know when the fix will be released.
