### ISSUE TITLE
UI Improvement: Display 0.01 steps for P instead of 0.1

### ISSUE THREAD

**Issue by SoulPictures** [cleanflight/cleanflight-configurator#314]
Hey there,

within betaflight is seems now possible to increase and decrease P in steps of 0.01 instead of the usual 0.1 steps within cleanflight. Would it be possible to change the display "step" from 0.1 to 0.01. 

It seems as if it would be easily possible within the "pid_tuning.html" file. I yet have no clue how to do it myself and commit it to the project, i am still to new to github for this sorry.

![stepsize](https://cloud.githubusercontent.com/assets/8168178/12075718/e5474aac-b189-11e5-86dc-25d1ab43b3d4.png)

**Comment by skaman82** [comment]
@SoulPictures This is not quite so easy. In the js. file is some weird math rounding action going on. This was too tricky for me as I looked into this.

**Comment by tricopterY** [comment]
This becomes significant if you are using pidLuxFloat Controller as per betaflight i.e calculations take decimal points into account. Otherwise all the PID terms are calculated/rounded as whole numbers (integers), and fractions/decimal points have no meaning. 
Summation of PID terms is always in whole numbers.
This is all about Resolution of PID terms and their real/over-all effect.
Happy flying.

**Comment by NightHawk32** [comment]
Greater resolution also requires firmware changes, there is a discussion ongoing: https://github.com/cleanflight/cleanflight/issues/1675

**Comment by martinbudden** [comment]
In betaflight`pidLuxFloat` has been converted to use PID integers values on the same scale as `pidMultiWiiRewrite`.
The same change is happening in Cleanflight v1.13.0.

So all of these steps should be set to 1 and max ranges set to 255.

See PR https://github.com/cleanflight/cleanflight/pull/2016
