### ISSUE TITLE
Prepare for next configurator release 1.3

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight-configurator#382]
### TODO
1. Create release notes
2. Wait for bug reports and make a list of them here.
### Release Candidate bug reports
1. Issue https://github.com/cleanflight/cleanflight-configurator/issues/383: PID values should be scaled 0 to 255
### DONE
1. None yet

**Comment by hydra** [comment]
Need to investigate why current sensor reads 65536 in latest configurator.  i noticed this when testing today.  not sure if it's MSP or firmware related yet.  Have someone else confirm this would be good.

**Comment by reedbn** [comment]
Issue #384 needs to be addressed

**Comment by skaman82** [comment]
@martinbudden here a list with things to do:
https://github.com/cleanflight/cleanflight-configurator/pull/362
https://github.com/cleanflight/cleanflight-configurator/pull/397
https://github.com/cleanflight/cleanflight-configurator/pull/399
https://github.com/cleanflight/cleanflight-configurator/pull/373
https://github.com/cleanflight/cleanflight-configurator/issues/381

NEW OSD Tab (because of that I would say we jump right to 1.3 instead 1.2.3.

Or maybe it is worth it to release 1.2.3. in the current state (that way users can benefit from advanced LED tab before the OSD stuff is ready (this can take some more weeks I think). @hydra What do you think?

**Comment by martinbudden** [comment]
Personally, if you are confident in the code, and you think you haven't introduced any bugs, I'd release 1.2.3 now.

**Comment by skaman82** [comment]
Yes, I am pretty confident that i didn't break anything :)

**Comment by skaman82** [comment]
@hydra I am also for releasing 1.2.3 now and then start to working on 1.3.0
