### ISSUE TITLE
LED Strip - Show colors as configured in the FC

### ISSUE THREAD

**Issue by Akfreak** [cleanflight/cleanflight-configurator#95]
Show colors on numbered color buttons (configurator issue, moved from fc firmware issue tracker)

**Comment by heathicus** [comment]
I just came here to make this same request.  Additionally, change the representations on the grid to show what color the "Orientation" light will be based on the orientation chosen rather than all green.

**Comment by joefarmer** [comment]
Me three!

**Comment by hydra** [comment]
@heathicus orientation colors are hard to repliate since they are only known by the fc and they depend on the mode.  the fc logic would have to be repeated in the UI.  If you want that please open a new issue.

This issue is for making the numbered color boxes show the colors used by the FC.  i.e. the colors that the cli `color` command shows.

**Comment by Jonny360** [comment]
Would this also allow customizing colors for arming/indicator, etc? Because that would be great.

**Comment by hydra** [comment]
@destos Wanna have a crack at this?

**Comment by destos** [comment]
@hydra How open are you to me re-working the led configuration interface to use react.js? I can see many potential cleanup and simplification opportunities by using is instead of straight dom manipulation via jQuery.

**Comment by skaman82** [comment]
@destos just give it a try. I would love to see with what you can come up.

**Comment by skaman82** [comment]
Mostly taken care of in https://github.com/cleanflight/cleanflight-configurator/pull/390

**Comment by skaman82** [comment]
This works now in the "special colors" section on the led tab
